# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{golden_retriever}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["DouglasMeyer"]
  s.date = %q{2010-02-03}
  s.description = %q{ Restful controllers will have their resources automatically loaded for them.}
  s.email = %q{DouglasYMan@Yahoo.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "lib/golden_retriever.rb",
     "test/nested_restful_controller_test.rb",
     "test/restful_controller_test.rb",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/DouglasMeyer/golden_retriever}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Retriever fetches your resources for you.}
  s.test_files = [
    "test/teststrap.rb",
     "test/nested_restful_controller_test.rb",
     "test/restful_controller_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<active_support>, [">= 2.3.0"])
    else
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<active_support>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<active_support>, [">= 2.3.0"])
  end
end

